name = "gilasartworker"
main = "worker/src/index.js"
compatibility_date = "2026-09-24"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "gilasartdatabase"
database_id = "3e6741e8-e50c-4c8d-b50a-33d9db2dfd4c"
migrations_dir = "database/migrations"

[vars]
APP_ORIGIN = "https://www.gilasart.ir"
FRONTEND_URL = "https://www.gilasart.ir"
PAYMENT_ENV = "production"

[triggers]
crons = ["*/15 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1
