-- Seed 12 fictional reviews for product 321 (gilas321)
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_001','مینا سلطانی','09321001');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_001',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_001',5,'کیفیت برش دستی عالی بود. قاب مشکی خیلی شیک دراومده روی دیوار خونه‌مون.',0,'1 بهمن 1402');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_002','بهرام عابدی','09321002');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_002',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_002',5,'ترکیب مس براق با قاب مشکی فوق‌العاده مدرن و زیباست.',0,'6 خرداد 1403');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_003','اردشیر محمودی','09321003');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_003',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_003',5,'تابلو خیلی سبک و محکمه. قابش هم کاملاً فیت شده.',0,'3 اردیبهشت 1403');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_004','رویا ملکی','09321004');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_004',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_004',5,'قیمت نسبت به کار دستی کمی بالاست. برش چقدر طول می‌کشه؟',0,'6 بهمن 1402');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_005','رویا مرادی','09321005');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_005',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_005',5,'کیفیت برش دستی عالی بود. قاب مشکی خیلی شیک دراومده روی دیوار خونه‌مون.',0,'4 مرداد 1393');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_006','کیان حیدری','09321006');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_006',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_006',5,'چرا اینقدر گرونه؟ مگه برش این‌ها چقدر طول می‌کشه؟ البته کیفیتش خوبه.',0,'4 اسفند 1399');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_007','محمد اسدی','09321007');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_007',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_007',5,'کار دست‌ساز عالیه. کی پیشنهاد ویژه یا تخفیف می‌ذارین؟',0,'6 فروردین 1397');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_008','آناهیتا آقایی','09321008');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_008',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_008',5,'کار دست‌ساز عالیه. کی پیشنهاد ویژه یا تخفیف می‌ذارین؟',0,'11 دی 1400');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_009','کیان کریمی','09321009');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_009',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_009',5,'کیفیت ساخت و ظرافت برش واقعاً قابل تقدیره. پیشنهاد ویژه.',0,'24 مهر 1399');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_010','امیر رضوی','09321010');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_010',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_010',5,'معرق مس عالیه. ای کاش سایز بزرگتر موجود بود و سفارش می‌دادم.',0,'14 بهمن 1399');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_011','داریوش رضایی','09321011');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_011',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_011',5,'قاب PVC با کیفیت و رنگ ثابت. خیلی راضی هستم.',0,'13 مرداد 1398');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas321_012','سینا حیدری','09321012');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas321_012',(SELECT id FROM products WHERE lower(sku)=lower('gilas321')),'review_seed_user_gilas321_012',5,'قیمت نسبت به کار دستی کمی بالاست. برش چقدر طول می‌کشه؟',0,'3 شهریور 1402');
