-- Seed 12 demo reviews for product 342 (gilas342)
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_001','شهرام زمانی','09342001');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_001',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_001',5,'ترکیب مس و قاب قهوه‌ای سوخته حس سنتی زیبایی می‌ده.',0,'15 مرداد 1405');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_002','حسین امیری','09342002');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_002',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_002',5,'معرق مس با قاب طلایی گلدارش مثل جواهر روی دیوار می‌مونه.',0,'3 آبان 1399');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_003','مجید کریمی','09342003');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_003',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_003',5,'خیلی زیباست. منتظر تخفیف‌های بعدی‌تون هستم.',0,'3 اسفند 1393');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_004','ناصر کریمی','09342004');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_004',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_004',5,'تابلو خیلی سبک و محکمه. قابش هم کاملاً فیت شده.',0,'28 تیر 1396');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_005','آریا زارعی','09342005');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_005',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_005',5,'کیفیت خوبه اما ارسال کمی دیر شد. ای کاش زودتر می‌فرستادین.',0,'30 فروردین 1398');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_006','گیتا باقری','09342006');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_006',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_006',5,'چرا اینقدر گرونه؟ مگه برش این‌ها چقدر طول می‌کشه؟ البته کیفیتش خوبه.',0,'13 آذر 1404');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_007','ابراهیم سلطانی','09342007');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_007',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_007',5,'قیمت نسبت به کار دستی کمی بالاست. برش چقدر طول می‌کشه؟',0,'22 آذر 1398');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_008','ریحانه جعفری','09342008');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_008',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_008',5,'برش دستی و دقیق، بدون هیچ ایرادی. کار تمیز و حرفه‌ای.',0,'7 آبان 1397');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_009','ناصر رضوی','09342009');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_009',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_009',5,'برش‌های دستی مس باعث شده هر تابلو منحصر به فرد باشه. عالیه.',0,'2 آبان 1402');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_010','بهروز باقری','09342010');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_010',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_010',5,'چرا قیمت اینقدر بالاست؟ زمان برش دستی این تابلوها چقدره؟',0,'4 شهریور 1393');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_011','امیر امیری','09342011');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_011',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_011',5,'کیفیت PVC قاب عالیه و رنگ طلایی گلدارش محو نمی‌شه.',0,'18 شهریور 1398');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas342_012','پروین رحمانی','09342012');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas342_012',(SELECT id FROM products WHERE lower(sku)=lower('gilas342')),'review_seed_user_gilas342_012',5,'معرق مس با این سطح از ظرافت واقعاً کم پیدا می‌شه.',0,'13 آبان 1401');
