-- Seed 12 fictional reviews for product 331 (gilas331)
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_001','کیان رستمی','09331001');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_001',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_001',5,'معرق مس عالیه. ای کاش سایز بزرگتر موجود بود و سفارش می‌دادم.',0,'29 فروردین 1397');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_002','امیرحسین شریفی','09331002');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_002',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_002',5,'تابلو دقیقاً مطابق عکس بود و حتی قشنگ‌تر. دستتون درد نکنه.',0,'26 تیر 1395');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_003','آریا حیدری','09331003');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_003',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_003',5,'تابلو زیباست ولی تأخیر در ارسال کمی ناراحت‌کننده بود.',0,'30 فروردین 1403');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_004','علیرضا جعفری','09331004');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_004',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_004',5,'قیمتش کمی بالاست. برش دستی چقدر زمان می‌بره که این قیمت درمیاد؟',0,'12 تیر 1403');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_005','محمدعلی مقدم','09331005');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_005',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_005',5,'این کار دست‌ساز ارزش هنری بالایی داره. خیلی خوشحالم از خرید.',0,'9 دی 1394');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_006','ترانه امیری','09331006');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_006',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_006',5,'جزئیات کار فوق‌العاده ظریفه. واقعاً کار استادانه‌ست.',0,'26 اردیبهشت 1393');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_007','ناصر سلطانی','09331007');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_007',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_007',5,'بسته‌بندی عالی بود و تابلو سالم به دستم رسید. ممنون.',0,'3 فروردین 1401');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_008','هانیه رضوی','09331008');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_008',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_008',5,'تابلو عالیه. ای کاش بزرگترش رو گرفته بودم، الان حس می‌کنم کوچیکه.',0,'25 اسفند 1404');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_009','بهار درویشی','09331009');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_009',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_009',5,'قاب قهوه‌ای سوخته با طرح معرق مس ترکیب بی‌نظیری شده. ممنون از کارتون.',0,'8 اسفند 1399');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_010','اکبر هاشمی','09331010');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_010',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_010',5,'قاب مشکی مات با درخشش مس ترکیب مدرنی ساخته. عاشقش شدم.',0,'17 مهر 1402');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_011','مهسا آقایی','09331011');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_011',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_011',5,'از خرید این معرق مس پشیمون نشدم. ارزش هر ریالی که دادم رو داره.',0,'18 مهر 1401');
INSERT OR IGNORE INTO users (id,name,phone) VALUES ('review_seed_user_gilas331_012','حسین علیزاده','09331012');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas331_012',(SELECT id FROM products WHERE lower(sku)=lower('gilas331')),'review_seed_user_gilas331_012',5,'معرق مس عالیه. ای کاش سایز بزرگتر موجود بود و سفارش می‌دادم.',0,'11 اسفند 1397');
