-- Seed 12 fictional reviews for product 335 (gilas335)
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_001','امیرحسین حیدری','09335001');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_001',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_001',5,'تابلو خیلی سبک و محکمه. قابش هم کاملاً فیت شده.',0,'5 تیر 1400');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_002','گیتا خلیلی','09335002');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_002',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_002',5,'ترکیب مس براق با قاب مشکی فوق‌العاده مدرن و زیباست.',0,'30 مهر 1401');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_003','سیروس رستمی','09335003');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_003',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_003',5,'کار قشنگیه ولی ای کاش سریع‌تر ارسال می‌کردین.',0,'20 دی 1402');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_004','آرش رستمی','09335004');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_004',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_004',5,'قاب طلایی گلدارش خیلی لوکس و شیکه. تابلو رو کامل کرده.',0,'13 فروردین 1402');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_005','علیرضا علیزاده','09335005');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_005',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_005',5,'تابلو زیباست ولی تأخیر در ارسال کمی ناراحت‌کننده بود.',0,'3 شهریور 1398');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_006','سعید هاشمی','09335006');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_006',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_006',5,'تابلو خیلی سبک و محکمه. قابش هم کاملاً فیت شده.',0,'22 آبان 1397');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_007','معصومه باقری','09335007');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_007',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_007',5,'قاب PVC خیلی مقاوم به نظر میاد و رنگش ثابت مونده.',0,'5 اردیبهشت 1394');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_008','جمشید جعفرزاده','09335008');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_008',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_008',5,'از خرید این معرق مس پشیمون نشدم. ارزش هر ریالی که دادم رو داره.',0,'1 دی 1401');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_009','لیلا غفاری','09335009');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_009',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_009',5,'رنگ قاب قهوه‌ای سوخته گرم و دلنشینه. با دکوراسیون چوبی عالی می‌شه.',0,'29 فروردین 1400');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_010','قاسم محمودی','09335010');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_010',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_010',5,'رنگ قاب قهوه‌ای سوخته با فضای سنتی خونه‌مون عالی ست شده.',0,'29 آبان 1396');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_011','امیرحسین درویشی','09335011');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_011',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_011',5,'از نزدیک که دیدم کیفیتش چند برابر عکس‌هاست. قاب قهوه‌ای سوخته خیلی گرمه.',0,'21 اردیبهشت 1403');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas335_012','بهرام خسروی','09335012');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas335_012',(SELECT id FROM products WHERE lower(sku)=lower('gilas335')),'review_seed_user_gilas335_012',5,'معرق مس عالیه. ای کاش سایز بزرگتر موجود بود و سفارش می‌دادم.',0,'27 اردیبهشت 1398');
