-- Seed 12 fictional reviews for product 336 (gilas336)
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_001','آرش نظری','09336001');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_001',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_001',5,'معرق مس با قاب طلایی گلدارش مثل جواهر روی دیوار می‌مونه.',0,'13 دی 1398');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_002','حدیث نصیری','09336002');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_002',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_002',5,'معرق مس با قاب طلایی گلدارش مثل جواهر روی دیوار می‌مونه.',0,'14 مهر 1397');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_003','پریسا رضوی','09336003');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_003',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_003',5,'تابلو دقیقاً مطابق عکس بود و حتی قشنگ‌تر. دستتون درد نکنه.',0,'4 دی 1396');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_004','سیروس توکلی','09336004');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_004',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_004',5,'ترکیب مس براق با قاب مشکی فوق‌العاده مدرن و زیباست.',0,'23 بهمن 1400');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_005','علیرضا رضایی','09336005');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_005',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_005',5,'تابلو دقیقاً مطابق عکس بود و حتی قشنگ‌تر. دستتون درد نکنه.',0,'5 بهمن 1399');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_006','جمشید باقری','09336006');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_006',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_006',5,'رنگ قاب قهوه‌ای سوخته گرم و دلنشینه. با دکوراسیون چوبی عالی می‌شه.',0,'2 اسفند 1394');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_007','جمشید درویشی','09336007');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_007',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_007',5,'این تابلو رو برای دفتر کارم گرفتم و همه همکاران تعریف کردن.',0,'12 بهمن 1401');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_008','یاسمن اسدی','09336008');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_008',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_008',5,'عالی بود. ای کاش سایز بزرگتری انتخاب کرده بودم.',0,'20 فروردین 1394');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_009','داریوش نوری','09336009');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_009',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_009',5,'برش‌های دستی مس باعث شده هر تابلو منحصر به فرد باشه. عالیه.',0,'12 خرداد 1400');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_010','آیدا ابراهیمی','09336010');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_010',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_010',5,'ترکیب مس براق با قاب مشکی فوق‌العاده مدرن و زیباست.',0,'9 دی 1396');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_011','نازنین حیدری','09336011');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_011',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_011',5,'رنگ قاب قهوه‌ای سوخته گرم و دلنشینه. با دکوراسیون چوبی عالی می‌شه.',0,'19 بهمن 1396');
INSERT OR IGNORE INTO users (id,name,mobile) VALUES ('review_seed_user_gilas336_012','احمد اسماعیلی','09336012');
INSERT OR IGNORE INTO reviews (id,product_id,user_id,rating,comment,approved,created_at) VALUES ('review_seed_gilas336_012',(SELECT id FROM products WHERE lower(sku)=lower('gilas336')),'review_seed_user_gilas336_012',5,'از خرید این معرق مس پشیمون نشدم. ارزش هر ریالی که دادم رو داره.',0,'14 آبان 1401');
