import {api} from '../services/api.js';
import {setupDataGrid} from '../components/Table.js';
const n=v=>new Intl.NumberFormat('fa-IR').format(Number(v||0));
export default function Discounts(){
 setTimeout(async()=>{const [pd,cd]=await Promise.all([api('/api/admin/products'),api('/api/admin/categories')]);document.querySelector('#d-products').innerHTML=(pd.items||[]).map(x=>'<option value="'+x.id+'">'+x.name+' — '+x.sku+'</option>').join('');document.querySelector('#d-category').innerHTML='<option value="">بدون دسته / کل محصولات</option>'+(cd.items||[]).map(x=>'<option value="'+x.id+'">'+x.name+'</option>').join('');document.querySelector('#discount-form').addEventListener('submit',submit);load()},0);
 async function load(){try{const d=await api('/api/admin/discounts'),el=document.querySelector('#discount-grid');el.innerHTML=(d.items||[]).map(x=>'<tr><td>'+x.title+'</td><td>'+(x.kind==='PERCENT'?'درصدی':'مبلغ ثابت')+'</td><td>'+n(x.value)+'</td><td>'+n(x.usage_count)+'</td><td>'+(x.active?'فعال':'غیرفعال')+'</td><td><button class="btn ghost edit" data-id="'+x.id+'">ویرایش</button> <button class="btn danger del" data-id="'+x.id+'">حذف</button></td></tr>').join('')||'<tr><td colspan="6">تخفیفی ثبت نشده است.</td></tr>';setupDataGrid('discount-grid');el.querySelectorAll('.edit').forEach(b=>b.onclick=()=>edit((d.items||[]).find(x=>x.id===b.dataset.id)));el.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(confirm('این تخفیف حذف شود؟')){await api('/api/admin/discounts/'+b.dataset.id,{method:'DELETE'});load()}})}catch(e){document.querySelector('#discount-error').textContent=e.message}}
 function edit(x){const f=document.querySelector('#discount-form');for(const [name,val] of Object.entries({title:x.title,kind:x.kind,value:x.value,minOrderIrt:x.min_order_irt,maxUses:x.max_uses||'',startsAt:x.starts_at?x.starts_at.slice(0,16):'',endsAt:x.ends_at?x.ends_at.slice(0,16):''})){const el=f.elements[name];if(el)el.value=val}f.elements.active.checked=!!x.active;f.dataset.id=x.id;document.querySelector('#discount-title').textContent='ویرایش تخفیف';document.querySelector('#d-products').value=(x.products||[]).map(y=>y.product_id);document.querySelector('#d-category').value=x.categories?.[0]?.category_id||''}
 async function submit(e){e.preventDefault();const f=e.currentTarget,b={title:f.elements.title.value,kind:f.elements.kind.value,value:Number(f.elements.value.value),minOrderIrt:Number(f.elements.minOrderIrt.value||0),maxUses:f.elements.maxUses.value||null,startsAt:f.elements.startsAt.value||null,endsAt:f.elements.endsAt.value||null,active:f.elements.active.checked,productIds:[...document.querySelector('#d-products').selectedOptions].map(x=>x.value),categoryId:document.querySelector('#d-category').value||null};try{const id=f.dataset.id;await api(id?'/api/admin/discounts/'+id:'/api/admin/discounts',{method:id?'PUT':'POST',body:JSON.stringify(b)});f.reset();delete f.dataset.id;document.querySelector('#discount-title').textContent='ایجاد تخفیف';await load()}catch(x){alert(x.message)}}
 const html='<div class="admin-page" dir="rtl"><div class="admin-title"><div><h2>تخفیفات</h2><span class="muted">تخفیف درصدی یا مبلغ ثابت برای محصول، دسته یا کل محصولات</span></div></div><div id="discount-error" class="error"></div><div class="panel"><h3 id="discount-title">ایجاد تخفیف</h3><form id="discount-form" class="form"><div class="form-grid"><label>عنوان<input name="title" required maxlength="160"></label><label>نوع<select name="kind"><option value="PERCENT">درصدی</option><option value="FIXED">مبلغ ثابت</option></select></label><label>مقدار<input name="value" type="number" min="0" required></label><label>حداقل خرید (ریال)<input name="minOrderIrt" type="number" min="0"></label><label>محدودیت استفاده<input name="maxUses" type="number" min="1"></label><label>شروع<input name="startsAt" type="datetime-local"></label><label>پایان<input name="endsAt" type="datetime-local"></label></div><label>محصولات هدف (چند انتخابی)<select id="d-products" multiple size="6"></select></label><label>دسته هدف<select id="d-category"></select></label><label class="check"><input name="active" type="checkbox" checked> فعال باشد</label><button class="btn primary">ذخیره تخفیف</button></form></div><div class="panel"><div class="table-scroll"><table class="admin-table"><thead><tr><th>عنوان</th><th>نوع</th><th>مقدار</th><th>مصرف</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody id="discount-grid"><tr><td colspan="6">در حال دریافت...</td></tr></tbody></table></div></div></div>';
 return html;
}
