import {api} from '../services/api.js';
import {setupDataGrid} from '../components/Table.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Tehran'}).format(new Date(String(v).replace(' ','T')+'Z')):'—';
export default function News(){
 setTimeout(load,0);
 async function load(){
  const d=await api('/api/admin/cms?section=news');const rows=d.items||[];
  const body=document.querySelector('#cms-grid');body.innerHTML=rows.map(x=>'<tr><td>'+esc(x.title)+'</td><td>'+esc(x.summary)+'</td><td>'+esc(x.active?'فعال':'غیرفعال')+'</td><td data-sort-value="'+esc(x.updated_at)+'">'+date(x.updated_at)+'</td><td><button class="btn ghost edit" data-id="'+esc(x.id)+'">ویرایش</button> <button class="btn danger del" data-id="'+esc(x.id)+'">حذف</button></td></tr>').join('')||'<tr><td colspan="5">رکوردی ثبت نشده است.</td></tr>';
  setupDataGrid('cms-grid',{dateColumns:[3]});
  document.querySelector('#cms-form').onsubmit=save;document.querySelector('#cms-clear').onclick=()=>{delete document.querySelector('#cms-form').dataset.id;load()};
  document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{const x=rows.find(y=>y.id===b.dataset.id);if(x){for(const [k,v] of Object.entries({id:x.id,title:x.title,slug:x.slug,summary:x.summary,body:x.body,phone:x.phone,mobile:x.mobile,address:x.address,mapUrl:x.map_url,sortOrder:x.sort_order,active:x.active})){const e=document.querySelector('#cms-form [name="'+k+'"]');if(e)e.value=v??''}document.querySelector('#cms-form').dataset.id=x.id;window.scrollTo({top:0,behavior:'smooth'})}});
  document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(!confirm('این رکورد حذف شود؟'))return;await api('/api/admin/cms/'+b.dataset.id,{method:'DELETE'});load()});
 }
 async function save(e){e.preventDefault();const f=new FormData(e.currentTarget),b=Object.fromEntries(f.entries());b.section='news';b.active=f.get('active')==='on';b.sortOrder=Number(b.sortOrder||0);const id=e.currentTarget.dataset.id;await api(id?'/api/admin/cms/'+id:'/api/admin/cms',{method:id?'PUT':'POST',body:JSON.stringify(b)});e.currentTarget.reset();delete e.currentTarget.dataset.id;load()}
 return '<div class="admin-page" dir="rtl"><div class="admin-title"><div><div class="eyebrow">GILAS ART CMS</div><h2>اخبار گیلاس آرت</h2><span class="muted">ثبت و ویرایش مستقیم محتوای سایت</span></div></div><div class="panel cms-editor"><form id="cms-form" class="form"><div class="form-grid"><label>عنوان<input name="title" required maxlength="180"></label><label>Slug<input name="slug" maxlength="160"></label><label>خلاصه<textarea name="summary" maxlength="500"></textarea></label><label>متن اصلی<textarea name="body" maxlength="12000"></textarea></label><label>ترتیب نمایش<input name="sortOrder" type="number" value="0"></label><label class="checkline"><input name="active" type="checkbox" checked> فعال</label></div><div class="toolbar"><button class="btn primary">ذخیره</button><button class="btn ghost" type="reset" id="cms-clear">پاک کردن فرم</button></div></form></div><div class="panel"><div class="sectionhead"><h3>رکوردهای ثبت‌شده</h3><span class="muted">جستجو، مرتب‌سازی و ویرایش از همین جدول</span></div><div class="table-scroll"><table class="admin-table"><thead><tr><th>عنوان</th><th>خلاصه</th><th>وضعیت</th><th>آخرین ویرایش</th><th>عملیات</th></tr></thead><tbody id="cms-grid"><tr><td colspan="5">در حال دریافت...</td></tr></tbody></table></div></div></div>';
}