import {admin,api} from '../services/api.js';
const money=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0));
export default function Products(){
 setTimeout(async()=>{try{const [pd,cd]=await Promise.all([admin.products(),api('/api/admin/categories')]);const cat=document.querySelector('#p-category');cat.innerHTML='<option value="">بدون دسته</option>'+(cd.items||[]).map(x=>`<option value="${x.id}">${x.name}</option>`).join('');render(pd.items||[])}catch(e){document.querySelector('#products-error').textContent=e.message}
 const form=document.querySelector('#product-form');form?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(form);try{await api('/api/admin/products',{method:'POST',body:JSON.stringify({name:f.get('name'),sku:f.get('sku'),slug:f.get('slug'),categoryId:f.get('categoryId')||null,priceIrt:Number(f.get('priceIrt')),stock:Number(f.get('stock')),description:f.get('description'),seoTitle:f.get('seoTitle'),seoDescription:f.get('seoDescription'),imagePath:f.get('imagePath'),imageAlt:f.get('imageAlt')})});form.reset();await refresh();alert('محصول ثبت شد')}catch(x){alert(x.message)}})},0);
 async function refresh(){const d=await admin.products();render(d.items||[])}
 function render(items){const el=document.querySelector('#products-table');if(!el)return;el.innerHTML=items.map(p=>`<tr><td><b>${p.name}</b><div class="muted">${p.slug}</div></td><td>${p.sku}</td><td>${money(p.price_irt)} ریال</td><td>${p.stock??0}</td><td><span class="pill">${p.active?'فعال':'غیرفعال'}</span></td><td><button class="btn ghost edit" data-id="${p.id}">ویرایش</button> <button class="btn danger del" data-id="${p.id}">حذف</button></td></tr>`).join('')||'<tr><td colspan="6">محصولی وجود ندارد.</td></tr>';el.querySelectorAll('.edit').forEach(b=>b.onclick=()=>edit(items.find(x=>x.id===b.dataset.id)));el.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(!confirm('حذف شود؟'))return;try{await api('/api/admin/products/'+b.dataset.id,{method:'DELETE'});refresh()}catch(e){alert(e.message)}})}
 function edit(p){const f=document.querySelector('#product-form');for(const [id,v] of [['p-name',p.name],['p-sku',p.sku],['p-slug',p.slug],['p-category',p.category_id||''],['p-price',p.price_irt],['p-stock',p.stock||0],['p-description',p.description||''],['p-seo-title',p.seo_title||''],['p-seo-description',p.seo_description||''],['p-image',p.image||'']]){const e=document.querySelector('#'+id);if(e)e.value=v}document.querySelector('#p-form-title').textContent='ویرایش محصول';f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f);try{await api('/api/admin/products/'+p.id,{method:'PUT',body:JSON.stringify({name:x.get('name'),categoryId:x.get('categoryId')||null,priceIrt:Number(x.get('priceIrt')),description:x.get('description'),active:true,seoTitle:x.get('seoTitle'),seoDescription:x.get('seoDescription'),imagePath:x.get('imagePath'),imageAlt:x.get('imageAlt')})});f.reset();f.onsubmit=null;document.querySelector('#p-form-title').textContent='افزودن محصول';await refresh();alert('ویرایش ذخیره شد')}catch(err){alert(err.message)}}}
 return `<div class="admin-page" dir="rtl"><div class="admin-title"><div><h2>محصولات</h2><span class="muted">کامل: اطلاعات، دسته، قیمت، موجودی، تصویر و SEO</span></div></div><div id="products-error" class="error"></div><div class="panel"><h3 id="p-form-title">افزودن محصول</h3><form id="product-form" class="form"><div class="form-grid"><label>نام<input id="p-name" name="name" required></label><label>SKU<input id="p-sku" name="sku" required></label><label>Slug<input id="p-slug" name="slug" required></label><label>دسته<select id="p-category" name="categoryId"></select></label><label>قیمت (ریال)<input id="p-price" name="priceIrt" type="number" min="0" required></label><label>موجودی<input id="p-stock" name="stock" type="number" min="0" required></label></div><label>توضیحات<textarea id="p-description" name="description" required></textarea></label><div class="form-grid"><label>SEO Title<input id="p-seo-title" name="seoTitle" maxlength="70"></label><label>SEO Description<textarea id="p-seo-description" name="seoDescription" maxlength="180"></textarea></label><label>مسیر تصویر<input id="p-image" name="imagePath" placeholder="/glsArt/art/example.svg"></label><label>Alt تصویر<input name="imageAlt"></label></div><button class="btn primary">ذخیره</button></form></div><div class="panel"><h3>کاتالوگ</h3><div class="table-scroll"><table class="admin-table"><thead><tr><th>محصول</th><th>SKU</th><th>قیمت</th><th>موجودی</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody id="products-table"><tr><td colspan="6">در حال دریافت...</td></tr></tbody></table></div></div></div>`;
}