const API=window.GILASART_API||'https://gilasartworker.gilasart-ir-ac.workers.dev';
const visitorSessionKey=(()=>{try{let k=localStorage.getItem('GilasArtVisitorSession');if(!k){const a=new Uint8Array(24);crypto.getRandomValues(a);k=Array.from(a,x=>x.toString(16).padStart(2,'0')).join('');localStorage.setItem('GilasArtVisitorSession',k)}return k}catch{return ''}})();
async function visitorHeartbeat(){if(!visitorSessionKey)return;try{await fetch(API+'/api/visitors/heartbeat',{method:'POST',credentials:'include',cache:'no-store',headers:{'content-type':'application/json'},body:JSON.stringify({sessionKey:visitorSessionKey})})}catch{}}
visitorHeartbeat();setInterval(visitorHeartbeat,60000);

let csrfToken='';
const app=document.querySelector('#app');let state={products:[],categories:[],user:null,roles:[],permissions:[],cart:null};
const icon=n=>({cart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 4h2l2.2 10.2a2 2 0 0 0 2 1.6h7.9a2 2 0 0 0 1.9-1.4L21 7H7"/><circle cx="10" cy="20" r="1.2"/><circle cx="18" cy="20" r="1.2"/> </svg>',user:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.2"/><path d="M5 21a7 7 0 0 1 14 0"/></svg>',search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>',send:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 4 18 8-18 8 3-8-3-8Z"/><path d="M6 12h9"/></svg>',check:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>',support:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3h11A2.5 2.5 0 0 1 20 5.5v7a2.5 2.5 0 0 1-2.5 2.5H11l-5.5 5V15A2.5 2.5 0 0 1 3 12.5v-7Z"/><path d="M7 8h10M7 11h6"/></svg>',plus:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>',close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>',clock:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/></svg>'}[n]||'');
const fa=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0));
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const safeUrl=v=>{try{const u=new URL(String(v||''),location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
const THEME_KEY='gilasart-theme';
function applyTheme(theme){const t=theme==='light'?'light':'dark';document.documentElement.dataset.theme=t;try{localStorage.setItem(THEME_KEY,t)}catch{}}
function initTheme(){let t='';try{t=localStorage.getItem(THEME_KEY)||''}catch{}applyTheme(t||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'))}
window.GilasArtTheme={toggle(){applyTheme(document.documentElement.dataset.theme==='light'?'dark':'light')},set:applyTheme};
initTheme();
let progressRequests=0,progressTimer=null;
function progressStart(){let bar=document.querySelector('#global-progress');if(!bar){bar=document.createElement('div');bar.id='global-progress';bar.innerHTML='<span></span><b>0%</b>';document.body.prepend(bar)}progressRequests++;bar.hidden=false;bar.querySelector('span').style.width='8%';bar.querySelector('b').textContent='0%';let value=8;clearInterval(progressTimer);progressTimer=setInterval(()=>{value=Math.min(92,value+Math.max(1,(92-value)/6));bar.querySelector('span').style.width=value+'%';bar.querySelector('b').textContent=Math.floor(value)+'%'},120)}
function progressEnd(){progressRequests=Math.max(0,progressRequests-1);if(progressRequests)return;clearInterval(progressTimer);const bar=document.querySelector('#global-progress');if(!bar)return;bar.querySelector('span').style.width='100%';bar.querySelector('b').textContent='100%';setTimeout(()=>{if(progressRequests===0)bar.hidden=true},220)}
window.GilasArtProgress={start:progressStart,end:progressEnd};
async function api(path,opt={}){progressStart();const headers={...(opt.headers||{})};if(opt.body)headers['content-type']='application/json';try{const r=await fetch(API+path,{credentials:'include',cache:'no-store',headers,...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'خطا');return d}finally{progressEnd()}}
function csrf(){return csrfToken||''}
function setSeo({title,description,image,type='website',jsonLd}={}){if(title){document.title=title;let t=document.querySelector('meta[name="description"]');if(!t){t=document.createElement('meta');t.name='description';document.head.appendChild(t)}t.content=description||'';const og=document.querySelector('meta[property="og:title"]');if(og)og.content=title;const od=document.querySelector('meta[property="og:description"]');if(od)od.content=description||'';if(image){let oi=document.querySelector('meta[property="og:image"]');if(!oi){oi=document.createElement('meta');oi.setAttribute('property','og:image');document.head.appendChild(oi)}oi.content=image}}document.querySelectorAll('script[data-gilasart-jsonld]').forEach(x=>x.remove());if(jsonLd){const s=document.createElement('script');s.type='application/ld+json';s.dataset.gilasartJsonld='1';s.textContent=JSON.stringify(jsonLd).replace(/</g,'\\u003c');document.head.appendChild(s)}}
function isAdminUser(){return state.roles?.includes("admin")||state.roles?.includes("super_admin")||state.roles?.includes("administrator")||state.roles?.includes("admin-role")}
function accountLink(){return state.user?`<a class="iconbtn profile-link" href="#/account" title="پروفایل کاربر">${icon('user')}<span>پروفایل</span></a>`:`<a class="iconbtn" href="#/account">${icon('user')}<span>ورود</span></a>`}
function layout(content){app.innerHTML=`<header class="top"><div class="wrap nav"><a class="brand" href="#/">گیلاس آرت<small>GILAS ART</small></a><nav class="links" aria-label="منوی اصلی"><a href="#/">خانه</a><a href="#/shop">فروشگاه</a><a href="#/about">درباره ما</a><a href="#/contact">تماس با ما</a><a href="#/news">اخبار</a><a href="#/articles">مقالات</a>${isAdminUser()?'<a class="admin-link" href="#/admin">کنترل پنل</a>':''}</nav><div class="spacer"></div><button class="theme-toggle" type="button" aria-label="تغییر حالت نمایش" title="روز / شب" onclick="window.GilasArtTheme&&window.GilasArtTheme.toggle()">◐ <span>روز/شب</span></button><a class="iconbtn cart-link" href="#/cart">${icon('cart')}<span>سبد خرید</span></a>${accountLink()}</div></header><main>${content}</main><footer class="footer"><div class="wrap footer-grid"><div><strong>گیلاس آرت</strong><p>هنر، انتخابی برای ماندن.</p></div><div><strong>خدمات</strong><a href="#/terms">قوانین سایت</a><a href="#/support">تیکت پشتیبانی</a><a href="#/contact">تماس با ما</a></div><div><strong>اعتماد</strong><div class="trust-badges"><span>نماد اعتماد</span><span>درگاه امن</span><span>پرداخت معتبر</span></div></div></div></footer>`}
function productCard(p){const image=safeUrl(p.image),flash=Number(p.flash_sale_active||p.flashSaleActive)===1&&p.flash_sale_ends_at;const shown=flash&&p.flash_sale_price_irt!==null&&p.flash_sale_price_irt!==undefined?Number(p.flash_sale_price_irt):Number(p.price_irt||0);return `<article class="card product-card">
<a href="#/product/${encodeURIComponent(p.slug||'')}"><div class="thumb">${image?`<img src="${escapeHtml(image)}" alt="${escapeHtml(p.name)}" loading="lazy">`:'اثر هنری'}${flash?`<span class="flash-badge">${icon('clock')} پیشنهاد شگفت‌انگیز</span>`:''}</div><div class="cardbody"><h3>${escapeHtml(p.name)}</h3><div class="muted">${escapeHtml(p.sku||'')}</div>${flash?`<div class="flash-timer" data-flash-end="${escapeHtml(p.flash_sale_ends_at)}" aria-label="زمان باقی‌مانده"></div>`:''}<div class="price">${fa(shown)} ریال</div>${flash&&p.flash_sale_price_irt!==null&&p.flash_sale_price_irt!==undefined?`<div class="muted flash-old">${fa(p.price_irt)} ریال</div>`:''}</div></a></article>`}
function startSkyAnimation(){
 const canvas=document.querySelector('#sky-canvas');if(!canvas)return;
 const ctx=canvas.getContext('2d');let raf=0,t=0;
 const resize=()=>{const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)};
 const stars=Array.from({length:55},(_,i)=>({x:(i*83)%100,y:(i*47)%72,r:i%3===0?1.4:.8,a:.25+(i%5)*.1}));
 const frame={x:62,y:51,w:210,h:150};
 function draw(){
  t+=.004;const r=canvas.getBoundingClientRect(),w=r.width,h=r.height;ctx.clearRect(0,0,w,h);
  const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#081525');sky.addColorStop(.58,'#17395a');sky.addColorStop(1,'#d6a875');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
  for(const s of stars){ctx.globalAlpha=s.a*(.65+.35*Math.sin(t*5+s.x));ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.x/100*w,s.y/100*h,s.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
  for(let i=0;i<4;i++){const x=((i*280-w*.15)+(t*35)% (w+420))-210,y=35+i*48;ctx.fillStyle='rgba(255,255,255,.10)';ctx.beginPath();ctx.ellipse(x,y,120,22,0,0,Math.PI*2);ctx.ellipse(x+80,y+4,95,18,0,0,Math.PI*2);ctx.fill()}
  const drift=Math.sin(t*1.7)*18;ctx.save();ctx.translate(w*.52+drift,h*.46+Math.sin(t*1.2)*8);ctx.rotate(Math.sin(t)*.025);
  ctx.strokeStyle='rgba(255,245,220,.9)';ctx.lineWidth=2;ctx.shadowBlur=24;ctx.shadowColor='rgba(255,225,160,.3)';ctx.strokeRect(-frame.w/2,-frame.h/2,frame.w,frame.h);ctx.shadowBlur=0;
  ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(-frame.w/2+8,-frame.h/2+8,frame.w-16,frame.h-16);ctx.restore();
  raf=requestAnimationFrame(draw)
 }
 resize();addEventListener('resize',resize,{passive:true});draw();canvas._cancel=()=>cancelAnimationFrame(raf)
}
async function home(){const [d,s,fs]=await Promise.all([api('/api/products?limit=8'),api('/api/settings').catch(()=>({settings:{}})),api('/api/flash-sales').catch(()=>({items:[]}))]);state.products=d.items||[];const ss=s.settings||{},flash=fs.items||[];setSeo({title:ss.seo_title||'گیلاس آرت | خرید تابلو و آثار هنری',description:ss.seo_description||ss.site_description});const flashSection=flash.length?`<section class="wrap flash-section"><div class="flash-head"><div><span class="eyebrow">LIMITED TIME</span><h2>پیشنهاد شگفت‌انگیز</h2><p>فرصت محدود برای انتخاب آثار منتخب</p></div><div class="flash-controls"><button class="icon-circle" id="flash-prev" aria-label="قبلی">‹</button><button class="icon-circle" id="flash-next" aria-label="بعدی">›</button></div></div><div id="flash-track" class="flash-track">${flash.map(productCard).join('')}</div></section>`:'';
layout(`<section class="wrap hero"><div class="hero-copy"><div class="eyebrow">هنر، با انتخابی شخصی</div><h1>آثاری برای خانه‌هایی که داستان دارند.</h1><p>گیلاس آرت یک فروشگاه فارسی برای کشف و خرید آثار هنری است؛ از انتخاب تا پرداخت، ساده و مطمئن.</p><div class="toolbar"><a class="btn primary" href="#/shop">مشاهده آثار</a><a class="btn ghost" href="#/about">درباره گیلاس آرت</a></div></div><div class="hero-sky" aria-label="قاب هنری شناور در آسمان"><canvas id="sky-canvas"></canvas><div class="sky-caption"><span class="pill">GILAS ART</span><strong>هنر در حرکت</strong><small>یک قاب، یک آسمان، یک لحظه.</small></div></div></section>${flashSection}<section class="wrap section"><div class="sectionhead"><h2>آخرین آثار</h2><a class="muted" href="#/shop">همه آثار ←</a></div><div class="grid">${state.products.slice(0,8).map(productCard).join('')||'<div class="panel">هنوز محصول فعالی منتشر نشده است.</div>'}</div></section>`);startSkyAnimation();startFlashTimers();const track=document.querySelector('#flash-track');if(track){const step=()=>{const first=track.querySelector('.card');return first?first.getBoundingClientRect().width+18:280};document.querySelector('#flash-prev').onclick=()=>track.scrollBy({left:-step(),behavior:'smooth'});document.querySelector('#flash-next').onclick=()=>track.scrollBy({left:step(),behavior:'smooth'});let timer=setInterval(()=>{if(!document.body.contains(track)){clearInterval(timer);return}const max=track.scrollWidth-track.clientWidth;if(track.scrollLeft>=max-10)track.scrollTo({left:0,behavior:'smooth'});else track.scrollBy({left:step(),behavior:'smooth'})},5000)}}
async function shop(){
 const pageSize=3;let offset=0,loading=false,done=false,query='',category='';let sentinel;
 const loadMore=async(reset=false)=>{
  if(loading||done)return;loading=true;
  if(reset){offset=0;done=false;document.querySelector('#results').innerHTML=''}
  try{
   const qs=new URLSearchParams({limit:String(pageSize),offset:String(offset)});
   if(query)qs.set('q',query);if(category)qs.set('category',category);
   const d=await api('/api/products?'+qs.toString());const items=d.items||[];
   document.querySelector('#empty')?.remove();
   document.querySelector('#results').insertAdjacentHTML('beforeend',items.map(productCard).join(''));
   offset+=items.length;if(items.length<pageSize)done=true;
   document.querySelector('#load-status').textContent=done?'همه آثار نمایش داده شد.':'با اسکرول پایین، آثار بیشتری نمایش داده می‌شود.';startFlashTimers(document.querySelector('#results'));
  }catch(e){document.querySelector('#load-status').textContent=e.message||'خطا در دریافت آثار.'}
  finally{loading=false}
 };
 const [cats]=await Promise.all([api('/api/categories')]);state.categories=cats.items||[];
 layout(`<section class="shop-hero"><div class="wrap shop-hero-inner"><div class="eyebrow">GILAS ART • COPPER INLAY</div><h1>هنرکده گیلاس آرت</h1><p>تولید کننده ی برتر تابلو های معرق مس در ایران</p><div class="hero-actions"><a class="btn primary" href="#/shop">مشاهده آثار</a><a class="btn ghost" href="#/about">درباره هنرکده</a></div></div><div class="shop-orbit" aria-hidden="true"><span></span><span></span><span></span></div></section>
 <section class="wrap page shop-page"><div class="sectionhead"><div><div class="eyebrow">GALLERY COLLECTION</div><h2>مجموعه تابلوها</h2><p class="muted">آثار به‌صورت زنده و تدریجی بارگذاری می‌شوند.</p></div></div>
 <div class="toolbar"><input id="q" class="search" placeholder="جستجوی اثر، نام یا کد محصول"><button class="btn primary" id="search">جستجو</button><button class="btn ghost cat active" data-id="">همه</button>${state.categories.map(c=>`<button class="btn ghost cat" data-id="${escapeHtml(c.id)}">${escapeHtml(c.name)}</button>`).join('')}</div>
 <div id="results" class="grid product-stream"></div><div id="sentinel" class="infinite-sentinel" aria-hidden="true"></div><div id="load-status" class="load-status">در حال آماده‌سازی گالری…</div><div id="empty" class="panel empty-state" hidden>نتیجه‌ای پیدا نشد.</div></section>`);
 sentinel=document.querySelector('#sentinel');
 const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))loadMore()}, {rootMargin:'500px 0px'});
 observer.observe(sentinel);
 const runSearch=()=>{query=document.querySelector('#q').value.trim();loadMore(true)};
 document.querySelector('#search').onclick=runSearch;
 document.querySelector('#q').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});
 document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{category=b.dataset.id||'';document.querySelectorAll('.cat').forEach(x=>x.classList.toggle('active',x===b));loadMore(true)});
 await loadMore();
}
async function product(slug){
 const d=await api('/api/products/'+encodeURIComponent(slug)),p=d.product||{},images=d.images||[],attributes=d.attributes||[];
 const image=safeUrl(p.image);
 setSeo({title:p.seo_title||p.name+' | گیلاس آرت',description:p.seo_description||p.description,image:image||undefined,jsonLd:{'@context':'https://schema.org','@type':'Product',name:p.name,description:p.description||'',sku:p.sku,image:images.map(x=>safeUrl(x.path)).filter(Boolean),offers:{'@type':'Offer',priceCurrency:'IRR',price:String(p.price_irt),availability:'https://schema.org/InStock',url:location.href}}});
 const mediaItems=images.map((x,i)=>({type:'image',src:safeUrl(x.path),alt:x.alt_text||p.name,index:i})).filter(x=>x.src);
 if(p.video_url)mediaItems.push({type:'video',src:safeUrl(p.video_url),alt:'ویدئوی محصول',index:mediaItems.length});
 const first=mediaItems[0]||null;
 const mediaHtml=item=>item?.type==='video'?'<video class="product-video-player" controls playsinline preload="metadata" src="'+escapeHtml(item.src)+'"><p>مرورگر شما از پخش ویدئو پشتیبانی نمی‌کند.</p></video>':item?.src?'<img src="'+escapeHtml(item.src)+'" alt="'+escapeHtml(item.alt||p.name)+'">':'<div class="product-media-empty">اثر هنری</div>';
 const optionHtml=attributes.map(a=>'<label class="product-option"><span>'+escapeHtml(a.name)+'</span><select data-attribute-id="'+escapeHtml(a.id)+'">'+a.options.map(o=>'<option value="'+escapeHtml(o.id)+'" data-delta="'+Number(o.price_delta_irt||0)+'" '+(o.is_default?'selected':'')+'>'+escapeHtml(o.name)+(Number(o.price_delta_irt||0)?' (+'+fa(o.price_delta_irt)+' ریال)':'')+'</option>').join('')+'</select></label>').join('');
 layout('<section class="wrap page product"><div class="product-gallery"><div id="product-media" class="product-media">'+mediaHtml(first)+'</div><div class="product-thumbs">'+mediaItems.map((x,i)=>x.type==='video'?'<button class="product-thumb video-thumb '+(i===0?'active':'')+'" data-index="'+i+'" aria-label="نمایش ویدئوی محصول"><span>▶</span><small>ویدئو</small></button>':'<button class="product-thumb '+(i===0?'active':'')+'" data-index="'+i+'" aria-label="نمایش تصویر '+(i+1)+'"><img src="'+escapeHtml(x.src)+'" alt=""></button>').join('')+'</div></div><div class="product-info"><span class="pill">'+escapeHtml(p.category_name||'اثر هنری')+'</span><h1>'+escapeHtml(p.name)+'</h1><p class="muted">'+escapeHtml(p.description||'')+'</p>'+(optionHtml?'<div class="panel product-options-panel"><h3>انتخاب ویژگی‌ها</h3><div class="product-options">'+optionHtml+'</div></div>':'')+'<div class="price product-live-price" id="product-live-price" style="font-size:24px;margin:24px 0">'+fa(p.price_irt)+' ریال</div><div class="muted" id="product-price-breakdown"></div><div class="toolbar"><button class="btn primary" id="add">افزودن به سبد</button><button class="btn ghost" id="fav">ذخیره</button></div><div class="panel"><h3>نظر خریداران</h3>'+((d.reviews||[]).map(r=>'<p><b>'+escapeHtml(r.name||'خریدار')+'</b> — '+('★'.repeat(Math.max(0,Math.min(5,Number(r.rating)||0))))+'<br>'+escapeHtml(r.body||'')+'</p>').join('')||'<span class="muted">هنوز نظری ثبت نشده است.</span>')+'</div></div></section>');
 document.querySelectorAll('.product-thumb').forEach(b=>b.onclick=()=>{const item=mediaItems[Number(b.dataset.index)];document.querySelector('#product-media').innerHTML=mediaHtml(item);document.querySelectorAll('.product-thumb').forEach(x=>x.classList.toggle('active',x===b))});
 const selections=()=>[...document.querySelectorAll('.product-option select')].map(x=>({attributeId:x.dataset.attributeId,optionId:x.value}));
 const recalc=()=>{let delta=0;document.querySelectorAll('.product-option option:checked').forEach(o=>delta+=Number(o.dataset.delta||0));const total=Number(p.price_irt||0)+delta;document.querySelector('#product-live-price').textContent=fa(total)+' ریال';document.querySelector('#product-price-breakdown').textContent=delta?'قیمت پایه: '+fa(p.price_irt)+' ریال + افزایش ویژگی‌ها: '+fa(delta)+' ریال':'';return total};
 document.querySelectorAll('.product-option select').forEach(x=>x.addEventListener('change',recalc));recalc();
 document.querySelector('#add').onclick=async()=>{try{await ensureLogin();await api('/api/cart',{method:'POST',body:JSON.stringify({productId:p.id,quantity:1,options:selections()}),headers:{'x-csrf-token':csrf()}});alert('به سبد خرید اضافه شد')}catch(e){alert(e.message)}};
 document.querySelector('#fav').onclick=async()=>{try{await ensureLogin();await api('/api/favorites',{method:'POST',body:JSON.stringify({productId:p.id}),headers:{'x-csrf-token':csrf()}});alert('ذخیره شد')}catch(e){alert(e.message)}};
}
async function ensureLogin(){if(state.user)return;await account();if(!state.user)throw new Error('ابتدا وارد حساب شوید')}
async function loadMe(){try{const d=await api('/api/me');state.user=d.user||null;state.roles=d.roles||[];state.permissions=d.permissions||[];csrfToken=d.csrfToken||csrfToken;return d}catch(e){return null}}
async function cart(){
 await loadMe();
 if(!state.user){layout('<section class="wrap page"><div class="panel"><h2>سبد خرید</h2><p>برای دیدن سبد خرید وارد حساب شوید.</p><a class="btn primary" href="#/account">ورود</a></div></section>');return}
 let d=await api('/api/cart'),couponCode='';
 const render=(p=d)=>{
  const items=p.items||[];
  const lines=items.map(x=>{
   const opts=x.selected_options?.length?'<div class="cart-options">'+x.selected_options.map(o=>escapeHtml(o.attributeName)+': '+escapeHtml(o.optionName)+(Number(o.priceDeltaIrt||0)?' (+'+fa(o.priceDeltaIrt)+' ریال)':'')).join(' · ')+'</div>':'';
   return '<div class="cartline"><div class="grow"><b>'+escapeHtml(x.name)+'</b><div class="muted">'+fa(x.unit_price_irt??x.price_irt)+' × '+fa(x.quantity)+' ریال</div>'+opts+'</div><button class="btn ghost del" data-id="'+escapeHtml(x.product_id)+'">حذف</button></div>';
  }).join('');
  const summary=items.length?'<hr><div class="sectionhead"><b>جمع کالاها</b><strong class="price">'+fa(p.subtotal_irt)+' ریال</strong></div><div class="coupon-box"><label>کد تخفیف خود را وارد کنید<input id="coupon-code" value="'+escapeHtml(couponCode)+'" placeholder="GLS________" autocomplete="off"></label><button class="btn primary" id="apply-coupon">اعمال کوپن</button><div id="coupon-message" class="muted"></div></div><div class="price-summary"><p>مبلغ اولیه: <b>'+fa(p.subtotal_irt)+' ریال</b></p><p>تخفیف: <b>'+fa(p.discount_irt)+' ریال</b></p><p>ارسال: <b>'+fa(p.shipping_irt)+' ریال</b></p><p>مبلغ قابل پرداخت: <strong class="price">'+fa(p.total_irt)+' ریال</strong></p></div><a class="btn primary" href="#/checkout">ادامه و ثبت سفارش</a>':'';
  layout('<section class="wrap page"><h1>سبد خرید</h1><div class="panel">'+(lines||'<p class="muted">سبد شما خالی است.</p>')+summary+'</div></section>');
 };
 document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{await api('/api/cart?productId='+b.dataset.id,{method:'DELETE',headers:{'x-csrf-token':csrf()}});cart()});
 document.querySelector('#apply-coupon')?.addEventListener('click',async()=>{const code=document.querySelector('#coupon-code').value.trim();try{const priced=await api('/api/cart/price',{method:'POST',body:JSON.stringify({code}),headers:{'x-csrf-token':csrf()}});couponCode=code;render(priced);const m=document.querySelector('#coupon-message');if(m)m.textContent='کوپن اعمال شد: '+fa(priced.coupon_discount_irt)+' ریال تخفیف';}catch(e){const m=document.querySelector('#coupon-message');if(m)m.textContent=e.message==='coupon_not_found'?'کد کوپن معتبر نیست.':e.message==='coupon_expired_or_inactive'?'کد کوپن منقضی یا غیرفعال است.':e.message==='coupon_usage_limit'?'سقف استفاده از این کوپن تکمیل شده است.':e.message==='coupon_already_used'?'این کوپن قبلاً برای حساب شما استفاده شده است.':e.message==='coupon_not_applicable'?'این کوپن برای محصولات سبد شما قابل استفاده نیست.':e.message==='coupon_min_order'?'حداقل مبلغ خرید این کوپن رعایت نشده است.':'اعمال کوپن با خطا مواجه شد.'}});
 render(d);
}
async function account(){await loadMe();if(state.user){layout(`<section class="wrap page"><div class="panel profile-panel"><div class="profile-head"><div class="profile-avatar">${icon('user')}</div><div><span class="eyebrow">MY ACCOUNT</span><h1>پروفایل کاربر</h1></div></div><div class="profile-data"><div><span>شماره موبایل</span><strong>${escapeHtml(state.user.mobile)}</strong></div><div><span>نام</span><strong>${escapeHtml(state.user.name||'کاربر گیلاس آرت')}</strong></div></div><div class="toolbar"><a class="btn ghost" href="#/support">${icon('support')} تیکت پشتیبانی</a>${isAdminUser()?'<a class="btn primary" href="#/admin">کنترل پنل</a>':''}<button class="btn ghost" id="logout">${icon('close')} خروج</button></div></div></section>`);document.querySelector('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST',headers:{'x-csrf-token':csrf()}});state.user=null;state.roles=[];state.permissions=[];location.hash='/'};return}
layout(`<section class="wrap page"><div class="panel login-panel" style="max-width:480px;margin:auto"><div class="profile-avatar">${icon('user')}</div><h1>ورود به گیلاس آرت</h1><p class="muted">کد یک‌بارمصرف برای شماره موبایل شما ارسال می‌شود.</p><div class="form"><label id="mobile-label">شماره موبایل<input id="mobile" inputmode="numeric" autocomplete="tel" maxlength="11" placeholder="09123456789"></label><button class="btn primary" id="send">${icon('send')} ارسال کد</button><div id="step"></div></div></div></section>`);
const send=document.querySelector('#send'),mobileEl=document.querySelector('#mobile'),mobileLabel=document.querySelector('#mobile-label'),step=document.querySelector('#step');
let countdownTimer=null;
const showMobile=()=>{mobileLabel.hidden=false;mobileLabel.removeAttribute('aria-hidden');mobileEl.disabled=false;send.hidden=false;send.disabled=false};
const hideMobile=()=>{mobileLabel.hidden=true;mobileLabel.setAttribute('aria-hidden','true');mobileEl.disabled=true;send.hidden=true;send.disabled=true};
const renderOtp=async(d)=>{step.innerHTML=`<div class="otp-session"><div class="otp-title"><span>کد تأیید ارسال شد</span><span id="otp-count" class="otp-count">02:00</span></div><label>کد تأیید<input id="otp" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]{6}" aria-label="کد تأیید"></label><button class="btn primary" id="verify">${icon('check')} ورود</button><button class="btn ghost resend-btn" id="resend" hidden>${icon('send')} ارسال مجدد کد</button><p id="otp-status" class="muted">کد پیامک‌شده را وارد کنید. در Chrome/Android می‌تواند با تأیید شما خودکار وارد شود.</p></div>`;
 const otp=document.querySelector('#otp'),verify=document.querySelector('#verify'),status=document.querySelector('#otp-status'),countEl=document.querySelector('#otp-count'),resend=document.querySelector('#resend');let verifying=false;
 clearInterval(countdownTimer);let left=Math.max(1,Number(d.expiresIn||120));const tick=()=>{const m=Math.floor(left/60),s=left%60;countEl.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(left<=0){clearInterval(countdownTimer);verify.disabled=true;resend.hidden=false;showMobile();status.textContent='زمان این کد تمام شد. برای دریافت کد جدید ارسال مجدد را بزنید.';return}left--;};tick();countdownTimer=setInterval(tick,1000);
 const finish=async(code)=>{if(verifying)return;code=String(code||'').replace(/\\D/g,'').slice(0,6);if(code.length!==6)return;otp.value=code;verifying=true;verify.disabled=true;status.textContent='در حال ورود...';try{const v=await api('/api/auth/verify-otp',{method:'POST',body:JSON.stringify({challengeId:d.challengeId,code})});state.user=v.user||null;state.roles=v.roles||[];state.permissions=v.permissions||[];csrfToken=v.csrfToken||csrfToken;clearInterval(countdownTimer);status.innerHTML='<span class="ok">ورود با موفقیت انجام شد.</span>';setTimeout(()=>{location.hash=isAdminUser()?'/admin':'/account';router()},180)}catch(e){verifying=false;verify.disabled=false;status.textContent=e.message||'کد واردشده صحیح نیست.';otp.focus()}};
 verify.onclick=()=>finish(otp.value);otp.addEventListener('input',()=>{otp.value=otp.value.replace(/\\D/g,'').slice(0,6);if(otp.value.length===6)finish(otp.value)});
 resend.onclick=async()=>{try{const mobile=mobileEl.value;hideMobile();resend.disabled=true;status.textContent='در حال ارسال کد جدید...';const nd=await api('/api/auth/request-otp',{method:'POST',body:JSON.stringify({mobile})});renderOtp(nd)}catch(e){resend.disabled=false;showMobile();status.textContent=e.message||'ارسال کد ناموفق بود.'}};
 if('OTPCredential' in window&&navigator.credentials?.get){try{const ac=new AbortController();setTimeout(()=>ac.abort(),130000);const credential=await navigator.credentials.get({otp:{transport:['sms']},signal:ac.signal});if(credential?.code)await finish(credential.code)}catch{}}
};
send.onclick=async()=>{hideMobile();step.innerHTML='<div class="otp-loading" role="status">در حال ارسال کد به پیامک…</div>';try{const mobile=mobileEl.value;const d=await api('/api/auth/request-otp',{method:'POST',body:JSON.stringify({mobile})});renderOtp(d)}catch(e){showMobile();step.innerHTML='<p class="error">'+escapeHtml(e.message||'ارسال کد ناموفق بود.')+'</p>';mobileEl.focus()}};
}
function jalaliDate(v){try{return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tehran'}).format(new Date(v))}catch{return ''}}
function startFlashTimers(root=document){root.querySelectorAll('.flash-timer[data-flash-end]').forEach(el=>{const end=new Date(el.dataset.flashEnd).getTime();const tick=()=>{const left=Math.max(0,end-Date.now());if(left<=0){el.textContent='پایان پیشنهاد';el.closest('.card')?.classList.add('flash-ended');return}const s=Math.floor(left/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;el.textContent=`${d?d+' روز ':''}${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};tick();const id=setInterval(()=>{if(!document.body.contains(el)){clearInterval(id);return}tick()},1000)})}
function renderFaq(items){return (items||[]).map((x,i)=>`<details class="faq-item" ${i===0?'open':''}><summary>${escapeHtml(x.question)}</summary><div>${escapeHtml(x.answer)}</div></details>`).join('')}
async function cmsStream(section){let offset=0,done=false,loading=false,query='';const pageSize=6;const title=section==='news'?'اخبار گیلاس آرت':'مقالات';layout(`<section class="wrap page cms-page"><div class="admin-title"><div><div class="eyebrow">GILAS ART</div><h1>${title}</h1></div></div><div class="toolbar cms-search"><input id="cms-q" class="search" placeholder="جستجو در ${section==='news'?'اخبار':'مقالات'}"><button class="btn primary" id="cms-search">${icon('search')} جستجو</button></div><div id="cms-stream" class="cms-stream"></div><div id="cms-sentinel" class="infinite-sentinel"></div><div id="cms-status" class="load-status">در حال دریافت…</div></section>`);const load=async(reset=false)=>{if(loading||done)return;loading=true;if(reset){offset=0;done=false;document.querySelector('#cms-stream').innerHTML='';}try{const qs=new URLSearchParams({section,limit:String(pageSize),offset:String(offset)});if(query)qs.set('q',query);const d=await api('/api/content?'+qs.toString());const items=d.items||[];document.querySelector('#cms-stream').insertAdjacentHTML('beforeend',items.map(x=>`<article class="panel cms-card"><div class="cms-date">${jalaliDate(x.published_at||x.created_at)}</div><span class="eyebrow">${section==='news'?'NEWS':'ARTICLE'}</span><h2>${escapeHtml(x.title)}</h2><p class="muted">${escapeHtml(x.summary||'')}</p><a class="btn ghost" href="#/${section==='articles'?'article':'news'}/${encodeURIComponent(x.slug)}">ادامه و جزئیات ←</a></article>`).join(''));offset+=items.length;done=items.length<pageSize;document.querySelector('#cms-status').textContent=done?(offset?'به انتهای فهرست رسیدیم.':'رکوردی پیدا نشد.'):'برای مشاهده موارد بیشتر اسکرول کنید.'}catch(e){document.querySelector('#cms-status').textContent=e.message||'خطا در دریافت محتوا.'}finally{loading=false}};const sentinel=document.querySelector('#cms-sentinel');const obs=new IntersectionObserver(es=>es.some(x=>x.isIntersecting)&&load(),{rootMargin:'500px'});obs.observe(sentinel);document.querySelector('#cms-search').onclick=()=>{query=document.querySelector('#cms-q').value.trim();load(true)};document.querySelector('#cms-q').onkeydown=e=>{if(e.key==='Enter'){query=e.target.value.trim();load(true)}};await load()}
async function cmsPage(section){if(section==='news'||section==='articles')return cmsStream(section);const d=await api('/api/content?section='+encodeURIComponent(section));const items=d.items||[];const title={about:'درباره ما',contact:'تماس با ما'}[section];let body='';if(section==='contact'){const x=items[0]||{};body='<div class="cms-contact-grid"><div class="panel"><h2>'+escapeHtml(x.title||title)+'</h2><p>'+escapeHtml(x.body||x.summary||'اطلاعات تماس هنوز ثبت نشده است.')+'</p><div class="contact-list">'+(x.phone?'<p><b>تلفن:</b> '+escapeHtml(x.phone)+'</p>':'')+(x.mobile?'<p><b>موبایل:</b> '+escapeHtml(x.mobile)+'</p>':'')+(x.address?'<p><b>آدرس هنرکده:</b> '+escapeHtml(x.address)+'</p>':'')+(x.map_url?'<a class="btn primary" target="_blank" rel="noopener noreferrer" href="'+escapeHtml(safeUrl(x.map_url))+'">مسیریابی روی نقشه</a>':'')+'</div></div></div>'}else body=items.slice(0,1).map(x=>'<article class="panel cms-rich"><span class="eyebrow">GILAS ART</span><h2>'+escapeHtml(x.title)+'</h2><p>'+escapeHtml(x.summary||'')+'</p><div>'+escapeHtml(x.body||'')+'</div></article>').join('')||'<div class="panel">اطلاعات درباره ما هنوز ثبت نشده است.</div>';layout('<section class="wrap page cms-page"><div class="admin-title"><div><div class="eyebrow">GILAS ART</div><h1>'+escapeHtml(title)+'</h1></div></div>'+body+'</section>')}
async function contentDetail(section,slug){const d=await api('/api/content/'+encodeURIComponent(section)+'/'+encodeURIComponent(slug));const x=d.item;if(!x){layout('<section class="wrap page"><div class="panel"><h2>محتوا پیدا نشد.</h2><a class="btn primary" href="#/'+section+'">بازگشت</a></div></section>');return}layout(`<section class="wrap page cms-page"><article class="panel cms-detail"><div class="cms-date">${jalaliDate(x.published_at||x.created_at)}</div><span class="eyebrow">${section==='news'?'NEWS':'ARTICLE'}</span><h1>${escapeHtml(x.title)}</h1><p class="lead">${escapeHtml(x.summary||'')}</p><div class="cms-body">${escapeHtml(x.body||'')}</div><a class="btn ghost" href="#/${section}">← بازگشت</a></article></section>`)}
async function support(){await loadMe();if(!state.user){layout('<section class="wrap page"><div class="panel login-required"><h1>پرتال CRM پشتیبانی</h1><p>برای ثبت و پیگیری تیکت، ابتدا وارد حساب خود شوید.</p><a class="btn primary" href="#/account">'+icon('user')+' ورود</a></div></section>');return}const f=await api('/api/faq');const d=await api('/api/support/tickets');layout(`<section class="wrap page support-portal"><div class="support-hero"><div><div class="eyebrow">CUSTOMER CRM</div><h1>پرتال پشتیبانی گیلاس آرت</h1><p class="muted">ثبت تیکت، مشاهده مرحله رسیدگی و ادامه گفت‌وگو در یک صفحه.</p></div><div class="support-orb">${icon('support')}</div></div><div class="support-grid"><div><div class="panel"><h2>${icon('plus')} ثبت تیکت جدید</h2><form id="ticket-form" class="form"><label>موضوع<input name="subject" maxlength="180" required></label><label>دسته‌بندی<select name="category"><option>عمومی</option><option>سفارش</option><option>پرداخت</option><option>محصول</option><option>سفارش سفارشی</option></select></label><label>اولویت<select name="priority"><option value="normal">عادی</option><option value="high">مهم</option><option value="low">کم</option></select></label><label>پیام<textarea name="message" required maxlength="10000"></textarea></label><button class="btn primary">${icon('send')} ثبت تیکت</button><div id="ticket-msg"></div></form></div><div class="panel"><div class="sectionhead"><h2>تیکت‌های من</h2><span class="muted">${fa((d.items||[]).length)} مورد</span></div><div class="ticket-list">${(d.items||[]).map(t=>`<a class="ticket-row" href="#/support/${encodeURIComponent(t.id)}"><div><strong>${escapeHtml(t.subject)}</strong><small>${escapeHtml(t.stage)} • ${jalaliDate(t.updated_at)}</small></div><span class="status-${escapeHtml(t.status)}">${t.status==='open'?'باز':'بسته'}</span></a>`).join('')||'<p class="muted">هنوز تیکتی ثبت نکرده‌اید.</p>'}</div></div></div><aside><div class="panel faq-panel"><div class="eyebrow">FAQ</div><h2>پرسش‌های متداول</h2>${renderFaq(f.items||[])}</div></aside></div></section>`);document.querySelector('#ticket-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const m=document.querySelector('#ticket-msg');try{await api('/api/support/tickets',{method:'POST',body:JSON.stringify({subject:f.get('subject'),category:f.get('category'),priority:f.get('priority'),message:f.get('message')}),headers:{'x-csrf-token':csrf()}});m.innerHTML='<span class="ok">تیکت ثبت شد.</span>';setTimeout(()=>support(),250)}catch(err){m.innerHTML='<span class="error">'+escapeHtml(err.message)+'</span>'}}}
async function supportDetail(id){await loadMe();if(!state.user){location.hash='/account';return}const d=await api('/api/support/tickets/'+encodeURIComponent(id));layout(`<section class="wrap page support-detail"><div class="panel"><div class="sectionhead"><div><span class="eyebrow">TICKET</span><h1>${escapeHtml(d.ticket.subject)}</h1><p class="muted">${escapeHtml(d.ticket.stage)} • ${d.ticket.status==='open'?'باز':'بسته'} • ${jalaliDate(d.ticket.created_at)}</p></div><a class="btn ghost" href="#/support">← همه تیکت‌ها</a></div><div class="ticket-thread">${(d.messages||[]).map(m=>`<div class="ticket-message ${m.author_type==='admin'?'from-admin':'from-user'}"><div class="message-meta">${m.author_type==='admin'?'پشتیبانی گیلاس آرت':'شما'} • ${jalaliDate(m.created_at)}</div><div>${escapeHtml(m.body)}</div></div>`).join('')}</div>${d.ticket.status==='open'?'<form id="reply-ticket" class="form"><label>پیام جدید<textarea name="message" required maxlength="10000"></textarea></label><button class="btn primary">'+icon('send')+' ارسال پاسخ</button><div id="reply-msg"></div></form>':'<div class="notice">این تیکت بسته شده است.</div>'}</div></section>`);document.querySelector('#reply-ticket')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/support/tickets/'+encodeURIComponent(id),{method:'POST',body:JSON.stringify({message:f.get('message')}),headers:{'x-csrf-token':csrf()}});supportDetail(id)}catch(err){document.querySelector('#reply-msg').textContent=err.message}})}
async function checkout(){
 await loadMe();if(!state.user){location.hash='/account';return}
 const idempotencyKey=(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)).replace(/-/g,'');
 const d=await api('/api/cart');let couponCode='';
 layout('<section class="wrap page"><div class="product"><div class="panel"><h1>ثبت سفارش</h1><div class="form"><label>نام گیرنده<input id="rn" value="'+escapeHtml(state.user.name||'')+'"></label><label>استان<input id="pr"></label><label>شهر<input id="ct"></label><label>نشانی<textarea id="ad"></textarea></label><label>کد پستی<input id="pc"></label><button class="btn primary" id="order">ثبت سفارش و پرداخت</button><div id="msg"></div></div></div><div class="panel"><h2>خلاصه</h2><p>جمع کالاها: <span id="sum-sub">'+fa(d.subtotal_irt)+'</span> ریال</p><p>تخفیف: <span id="sum-dis">'+fa(d.discount_irt)+'</span> ریال</p><p>ارسال: <span id="sum-ship">'+fa(d.shipping_irt)+'</span> ریال</p><strong class="price">مبلغ نهایی: <span id="sum-total">'+fa(d.total_irt)+'</span> ریال</strong><label>کد کوپن<input id="checkout-coupon" placeholder="GLS________"></label><button class="btn ghost" id="checkout-apply">اعمال کوپن</button><div id="checkout-coupon-msg" class="muted"></div></div></div></section>');
 document.querySelector('#checkout-apply').onclick=async()=>{const code=document.querySelector('#checkout-coupon').value.trim();try{const p=await api('/api/cart/price',{method:'POST',body:JSON.stringify({code}),headers:{'x-csrf-token':csrf()}});couponCode=code;document.querySelector('#sum-dis').textContent=fa(p.discount_irt);document.querySelector('#sum-ship').textContent=fa(p.shipping_irt);document.querySelector('#sum-total').textContent=fa(p.total_irt);document.querySelector('#checkout-coupon-msg').textContent='کوپن معتبر است.'}catch(e){document.querySelector('#checkout-coupon-msg').textContent='کوپن معتبر نیست یا قابل استفاده نیست.'}};
 document.querySelector('#order').onclick=async()=>{try{const a=await api('/api/addresses',{method:'POST',body:JSON.stringify({recipientName:document.querySelector('#rn').value,province:document.querySelector('#pr').value,city:document.querySelector('#ct').value,address:document.querySelector('#ad').value,postalCode:document.querySelector('#pc').value}),headers:{'x-csrf-token':csrf()}});const o=await api('/api/orders',{method:'POST',body:JSON.stringify({addressId:a.addressId,idempotencyKey,couponCode}),headers:{'x-csrf-token':csrf()}});const pay=await api('/api/orders/'+o.orderId+'/pay',{method:'POST',headers:{'x-csrf-token':csrf()}});location.href=pay.url}catch(e){document.querySelector('#msg').innerHTML='<span class="error">'+escapeHtml(e.message)+'</span>'}};
}
async function router(){const p=location.hash.slice(2).split('/');try{if(!p[0])return home();if(p[0]==='admin'){const base=location.pathname.includes('/glsArt/')?'/glsArt':'';const {default:AdminApp}=await import(base+'/admin/AdminApp.js?v=20260928.3');await loadMe();if(!isAdminUser()){location.hash='/account';return}app.innerHTML=AdminApp();return}if(p[0]==='shop')return shop();if(p[0]==='product')return product(p[1]);if(p[0]==='cart')return cart();if(p[0]==='account')return account();if(p[0]==='checkout')return checkout();if(p[0]==='about'||p[0]==='contact')return cmsPage(p[0]);if(p[0]==='article'&&p[1])return contentDetail('articles',decodeURIComponent(p[1]));if(p[0]==='news'&&p[1])return contentDetail('news',decodeURIComponent(p[1]));if(p[0]==='news'||p[0]==='articles')return cmsPage(p[0]);if(p[0]==='terms'){layout('<section class="wrap page"><div class="panel"><h1>قوانین سایت</h1><p>ثبت سفارش و پرداخت به معنی پذیرش قوانین و شرایط فروش گیلاس آرت است.</p></div></section>');return}if(p[0]==='support')return p[1]?supportDetail(decodeURIComponent(p[1])):support();if(p[0]==='payment'){layout(`<section class="wrap page"><div class="panel"><h1>${p[1]==='success'?'پرداخت با موفقیت تایید شد':'پرداخت ناموفق بود'}</h1><a class="btn primary" href="#/">بازگشت به فروشگاه</a></div></section>`);return}home()}catch(e){layout(`<section class="wrap page"><div class="panel"><h2>خطا</h2><p class="error">${escapeHtml(e.message)}</p></div></section>`)}}window.addEventListener('hashchange',async()=>{await loadMe();router()});loadMe().then(router);