const API=window.GILASART_API||'https://gilasartworker.gilasart-ir-ac.workers.dev';
const PROTECTED_ACTION='gilasart_form';
let siteKey='',token='',widget=null,ready=false,loading=null;
const isProtected=p=>p==='/api/auth/request-otp'||p==='/api/support/tickets'||p.startsWith('/api/support/tickets/')||p.startsWith('/api/products/')&&p.endsWith('/reviews');
async function loadScript(){if(window.turnstile)return window.turnstile;if(loading)return loading;loading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.defer=true;s.onload=()=>resolve(window.turnstile);s.onerror=()=>reject(new Error('captcha_script_failed'));document.head.appendChild(s)});return loading}
function buttons(form){return form?[...form.querySelectorAll('button[type="submit"],button:not([type])')]:[]}
function setEnabled(form,enabled,standaloneButton=null){if(standaloneButton){standaloneButton.disabled=!enabled;standaloneButton.dataset.captchaManaged='1'}buttons(form).forEach(b=>{b.dataset.captchaManaged='1';b.disabled=!enabled})}
function ensureBox(target){let box=target.querySelector('.gilasart-captcha');if(!box){box=document.createElement('div');box.className='gilasart-captcha';box.setAttribute('aria-label','تأیید امنیتی');target.appendChild(box)}return box}
async function mount(target,form,standaloneButton=null){if(target.dataset.captchaMounted||!target.isConnected)return;target.dataset.captchaMounted='1';setEnabled(form,false,standaloneButton);const box=ensureBox(target);try{if(!siteKey){const r=await fetch(API+'/api/security/turnstile-config',{credentials:'omit',cache:'no-store'});if(!r.ok)throw new Error('captcha_config_failed');const d=await r.json();siteKey=String(d.siteKey||'')}if(!siteKey)throw new Error('captcha_not_configured');const ts=await loadScript();widget=ts.render(box,{sitekey:siteKey,theme:'auto',size:'flexible',action:PROTECTED_ACTION,callback:t=>{token=t;ready=true;setEnabled(form,true,standaloneButton)},'expired-callback':()=>{token='';ready=false;setEnabled(form,false,standaloneButton)},'error-callback':()=>{token='';ready=false;setEnabled(form,false,standaloneButton)}})}catch(e){box.innerHTML='<span class="error">تأیید امنیتی در دسترس نیست؛ لطفاً کمی بعد دوباره تلاش کنید.</span>';setEnabled(form,false,standaloneButton)}}
function scan(){const accountButton=document.querySelector('#send');if(accountButton&&!accountButton.dataset.captchaMounted){accountButton.disabled=true;const host=accountButton.parentElement||accountButton;mount(host,null,accountButton);accountButton.dataset.captchaStandalone='1'}document.querySelectorAll('#ticket-form,#reply-ticket,#review-form').forEach(f=>{const host=f.querySelector('.captcha-host')||f;mount(host,f)})}
const originalFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:(input?.url||'');let path='';try{path=new URL(url,location.href).pathname}catch{}if(!isProtected(path))return originalFetch(input,init);if(!ready||!token)throw new Error('لطفاً ابتدا تأیید امنیتی را انجام دهید.');const next={...init,headers:{...(init.headers||{})}};let body=next.body;if(typeof body==='string'){try{const data=JSON.parse(body);data.captchaToken=token;next.body=JSON.stringify(data)}catch{}}else if(body instanceof FormData){body.set('captchaToken',token)}else if(!body){next.body=JSON.stringify({captchaToken:token});next.headers['content-type']='application/json'}try{return await originalFetch(input,next)}finally{token='';ready=false;document.querySelector('#send')?.setAttribute('disabled','');document.querySelectorAll('#ticket-form button[type="submit"],#reply-ticket button[type="submit"],#review-form button[type="submit"]').forEach(b=>b.disabled=true);try{if(widget&&window.turnstile)window.turnstile.reset(widget)}catch{}}};
const observer=new MutationObserver(scan);observer.observe(document.documentElement,{subtree:true,childList:true});scan();
window.GilasArtCaptcha={scan,reset(){token='';ready=false;try{window.turnstile?.reset(widget)}catch{}scan()}};
