const API=window.GILASART_API||'https://gilasartworker.gilasart-ir-ac.workers.dev';
let token='',answer='',widget=null,ready=false,loading=null,loginButton=null;
const isProtected=p=>p==='/api/auth/request-otp'||p==='/api/support/tickets'||p.startsWith('/api/support/tickets/')||p.startsWith('/api/products/')&&p.endsWith('/reviews');
function buttons(form){return form?[...form.querySelectorAll('button[type="submit"],button:not([type])')]:[]}
function normalizeDigits(v){return String(v||'').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)))}
function setEnabled(form,enabled,standaloneButton=null){if(standaloneButton){loginButton=standaloneButton;standaloneButton.dataset.captchaManaged='1';standaloneButton.disabled=!enabled}buttons(form).forEach(b=>{b.dataset.captchaManaged='1';b.disabled=!enabled})}
function ensureBox(target){let box=target.querySelector('.gilasart-captcha');if(!box){box=document.createElement('div');box.className='gilasart-captcha';box.setAttribute('role','group');box.setAttribute('aria-label','تأیید امنیتی');target.appendChild(box)}return box}
async function getChallenge(){const r=await fetch(API+'/api/security/captcha',{credentials:'omit',cache:'no-store'});if(!r.ok)throw new Error('captcha_unavailable');const d=await r.json();if(!d.token||!d.question)throw new Error('captcha_unavailable');return d}
async function mount(target,form,standaloneButton=null){if(!target?.isConnected||target.dataset.captchaMounted)return;target.dataset.captchaMounted='1';setEnabled(form,false,standaloneButton);const box=ensureBox(target);box.innerHTML='<span class="captcha-loading">در حال آماده‌سازی سؤال امنیتی…</span>';try{const d=await getChallenge();token=String(d.token);ready=false;box.innerHTML='<div class="math-captcha"><label>برای ادامه، حاصل زیر را وارد کنید <b class="math-question"></b><input class="math-answer" inputmode="numeric" autocomplete="off" maxlength="2" aria-label="پاسخ کپچا" placeholder="پاسخ"></label><button type="button" class="btn ghost math-refresh" aria-label="سؤال جدید">سؤال جدید</button><span class="captcha-hint">مثلاً اگر ۳ + ۵ باشد، عدد ۸ را وارد کنید.</span></div>';const q=box.querySelector('.math-question'),input=box.querySelector('.math-answer'),refresh=box.querySelector('.math-refresh');q.textContent=d.question;const validate=()=>{answer=normalizeDigits(input.value).replace(/\\D/g,'').slice(0,2);input.value=answer;ready=/^\\d{1,2}$/.test(answer);setEnabled(form,ready,standaloneButton)};input.addEventListener('input',validate);refresh.onclick=async()=>{setEnabled(form,false,standaloneButton);input.disabled=true;try{const nd=await getChallenge();token=String(nd.token);answer='';ready=false;q.textContent=nd.question;input.value='';}catch{box.querySelector('.captcha-hint').textContent='دریافت سؤال جدید ناموفق بود؛ صفحه را تازه‌سازی کنید.'}finally{input.disabled=false;input.focus();setEnabled(form,false,standaloneButton)}};input.focus()}catch(e){box.innerHTML='<span class="error">تأیید امنیتی در دسترس نیست؛ لطفاً صفحه را تازه‌سازی کنید.</span>';setEnabled(form,false,standaloneButton)}}
function scan(){const accountButton=document.querySelector('#send');if(accountButton&&!accountButton.dataset.captchaMounted){accountButton.disabled=true;const host=accountButton.closest('.form')?.querySelector('.captcha-host')||accountButton.closest('.form')||accountButton.parentElement||accountButton;mount(host,null,accountButton)}document.querySelectorAll('#ticket-form,#reply-ticket,#review-form').forEach(f=>{const host=f.querySelector('.captcha-host')||f;mount(host,f)})}
const originalFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:(input?.url||'');let path='';try{path=new URL(url,location.href).pathname}catch{}if(!isProtected(path))return originalFetch(input,init);if(!ready||!token||!answer)throw new Error('لطفاً پاسخ CAPTCHA را وارد کنید.');const next={...init,headers:{...(init.headers||{})}};let body=next.body;if(typeof body==='string'){try{const data=JSON.parse(body);data.captchaToken=token;data.captchaAnswer=answer;next.body=JSON.stringify(data)}catch{}}else if(body instanceof FormData){body.set('captchaToken',token);body.set('captchaAnswer',answer)}else{next.body=JSON.stringify({captchaToken:token,captchaAnswer:answer});next.headers['content-type']='application/json'}try{return await originalFetch(input,next)}finally{token='';answer='';ready=false;document.querySelector('#send')?.setAttribute('disabled','');document.querySelectorAll('#ticket-form button[type="submit"],#reply-ticket button[type="submit"],#review-form button[type="submit"]').forEach(b=>b.disabled=true)}};
const observer=new MutationObserver(scan);observer.observe(document.documentElement,{subtree:true,childList:true});scan();
window.GilasArtCaptcha={scan,isReady(){return ready&&!!token&&!!answer},reset(){token='';answer='';ready=false;if(loginButton)loginButton.disabled=true;scan()}};