const STATUS_LABELS={PENDING:'در انتظار پرداخت',PAID:'پرداخت شد',PROCESSING:'در حال پردازش',SHIPPED:'ارسال شد',DELIVERED:'تحویل شد',CANCELLED:'لغو شد',FAILED:'ناموفق'};
const money=v=>new Intl.NumberFormat('fa-IR').format(Number(v||0));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateFa=v=>{if(!v)return '-';const d=new Date(String(v).replace(' ','T')+(String(v).endsWith('Z')?'':'Z'));return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'medium',timeStyle:'short'}).format(d)};
const paidStatuses=new Set(['PAID','PROCESSING','SHIPPED','DELIVERED']);
function invoiceTitle(status){return paidStatuses.has(String(status||'').toUpperCase())?'فاکتور فروش':'پیش‌فاکتور فروش'}
function openInvoice(order,invoiceSettings={}){
 const o=order||{},items=Array.isArray(o.items)?o.items:[],status=String(o.status||'PENDING').toUpperCase();
 const sellerName=invoiceSettings.sellerName||invoiceSettings.invoice_store_name||'فروشگاه صنایع دستی گیلاس آرت';
 const totalQty=items.reduce((n,x)=>n+Number(x.quantity||0),0);
 const subtotal=Number(o.subtotal_irt||items.reduce((n,x)=>n+Number(x.line_total_irt||0),0));
 const shipping=Number(o.shipping_irt||0),discount=Number(o.discount_irt||0),total=Number(o.total_irt||0);
 const customerName=o.recipient_name||o.name||'کاربر گیلاس آرت';
 const customerPhone=o.address_mobile||o.mobile||'-';
 const customerAddress=[o.province,o.city,o.address].filter(Boolean).join('، ')||'ثبت نشده';
 const base=location.pathname.includes('/glsArt/')?'/glsArt':'';
 const resolveAssetPath=(value,fallback)=>{
  const raw=String(value||fallback||'').trim();
  if(!raw)return '';
  try{
   if(raw.startsWith('http://')||raw.startsWith('https://'))return raw;
   if(raw.startsWith('/'))return new URL(raw,location.origin).href;
   return new URL(raw,location.origin+(base?base+'/':'/')).href;
  }catch{return new URL(fallback,location.origin+(base?base+'/':'/')).href}
 };
 const logoPath=resolveAssetPath(window.GILASART_INVOICE_LOGO||invoiceSettings.logoPath||invoiceSettings.invoice_logo_path,base+'/invoice/logo.svg');
 const signaturePath=resolveAssetPath(window.GILASART_INVOICE_SIGNATURE||invoiceSettings.signaturePath||invoiceSettings.invoice_signature_path,base+'/invoice/stamp-signature.png');
 const rows=items.map((x,i)=>'<tr><td>'+money(i+1)+'</td><td><strong>'+esc(x.name)+'</strong><small>'+esc(x.sku||'')+'</small></td><td>'+money(x.quantity)+'</td><td>'+money(x.unit_price_irt)+' ریال</td><td>'+money(x.line_total_irt)+' ریال</td></tr>').join('');
 const html='<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>'+esc(invoiceTitle(status))+' | '+esc(String(o.id||'').slice(-10))+'</title><style>'+
 '@import url("https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css");'+
 '*{box-sizing:border-box}body{margin:0;background:#f1eee8;color:#292722;font-family:Vazirmatn,Tahoma,sans-serif;line-height:1.8}.sheet{width:210mm;min-height:297mm;margin:12mm auto;background:#fff;padding:14mm 15mm 12mm;box-shadow:0 10px 35px #0002;position:relative}.head{text-align:center;border-bottom:2px solid #b58a42;padding-bottom:16px}.brand{display:flex;flex-direction:column;align-items:center;gap:5px}.logo{width:180px;height:90px;object-fit:contain}.brand strong{font-size:17px}.title{text-align:center}.title h1{margin:5px 0 0;color:#8c6528;font-size:26px}.title p{margin:2px 0 0;font-size:11px;color:#777}.meta{text-align:left;font-size:11px;min-width:120px}.meta b{display:block;color:#8c6528}.boxes{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.box{border:1px solid #ddd6ca;border-radius:8px;overflow:hidden}.box h3{margin:0;padding:6px 9px;background:#f6f1e8;color:#795824;font-size:13px}.box .body{padding:8px 10px;min-height:105px;font-size:11px}.line{display:flex;gap:6px;margin:2px 0}.line b{min-width:78px;color:#6f675c}.items{margin-top:14px;width:100%;border-collapse:collapse;font-size:10.5px}.items th{background:#342f28;color:#fff;font-weight:600}.items th,.items td{border:1px solid #d9d2c7;padding:6px;text-align:center}.items td:nth-child(2){text-align:right}.items td small{display:block;color:#8b847b}.totals{margin-top:10px;margin-right:auto;width:48%;border-collapse:collapse;font-size:11px}.totals td{border:1px solid #ddd6ca;padding:5px}.totals td:last-child{text-align:left;font-weight:700}.grand{background:#f4ead6;color:#714e19;font-size:13px}.footer{display:flex;justify-content:space-between;align-items:flex-end;margin-top:28px;min-height:120px;border-top:1px solid #ddd6ca;padding-top:10px}.note{font-size:9px;color:#777;max-width:60%}.sign{text-align:center;width:230px;min-height:120px}.sign img{width:220px;height:115px;max-width:220px;max-height:115px;object-fit:contain}.sign .fallback{border-top:1px solid #999;padding-top:4px;color:#777;font-size:9px}.printbar{position:fixed;top:14px;right:14px;display:flex;gap:8px}.printbar button{border:0;border-radius:8px;padding:9px 14px;background:#8c6528;color:#fff;font-family:inherit;cursor:pointer}.printbar .close{background:#4b4740}@media print{body{background:#fff}.sheet{margin:0;box-shadow:none;width:210mm;min-height:297mm}.printbar{display:none}@page{size:A4;margin:0}}@media(max-width:900px){.sheet{width:calc(100% - 20px);padding:20px}.boxes{grid-template-columns:1fr}.totals{width:100%}}'+
 '</style></head><body><div class="printbar"><button onclick="window.print()">چاپ / ذخیره PDF</button><button class="close" onclick="window.close()">بستن</button></div><main class="sheet"><header class="head"><div class="brand"><img class="logo" src="'+esc(logoPath)+'" onerror="this.style.display=\'none\'"></div><div class="title"><h1>'+esc(invoiceTitle(status))+'</h1><p>صنایع دستی و آثار هنری گیلاس آرت</p></div><div class="meta"><b>شماره سفارش</b>'+esc(o.id||'-')+'<br><b>تاریخ</b>'+dateFa(o.created_at)+'</div></header>'+
 '<section class="boxes"><div class="box"><h3>مشخصات فروشنده</h3><div class="body"><div class="line"><b>نام فروشگاه:</b><span>'+esc(sellerName)+'</span></div><div class="line"><b>شناسه ملی:</b><span>'+esc(invoiceSettings.nationalId||invoiceSettings.invoice_national_id||'ثبت نشده')+'</span></div><div class="line"><b>کد اقتصادی:</b><span>'+esc(invoiceSettings.economicCode||invoiceSettings.invoice_economic_code||'ثبت نشده')+'</span></div><div class="line"><b>شماره ثبت:</b><span>'+esc(invoiceSettings.registrationNumber||invoiceSettings.invoice_registration_number||'ثبت نشده')+'</span></div><div class="line"><b>تلفن:</b><span>'+esc(invoiceSettings.phone||invoiceSettings.invoice_phone||'ثبت نشده')+'</span></div><div class="line"><b>تلفن همراه:</b><span>'+esc(invoiceSettings.mobile||invoiceSettings.invoice_mobile||'ثبت نشده')+'</span></div><div class="line"><b>کد پستی:</b><span>'+esc(invoiceSettings.postalCode||invoiceSettings.invoice_postal_code||'ثبت نشده')+'</span></div><div class="line"><b>آدرس:</b><span>'+esc(invoiceSettings.address||invoiceSettings.invoice_address||'ثبت نشده')+'</span></div></div></div><div class="box"><h3>مشخصات مشتری</h3><div class="body"><div class="line"><b>نام و نام خانوادگی:</b><span>'+esc(customerName)+'</span></div><div class="line"><b>تلفن:</b><span>'+esc(customerPhone)+'</span></div><div class="line"><b>آدرس:</b><span>'+esc(customerAddress)+'</span></div><div class="line"><b>وضعیت:</b><span>'+esc(STATUS_LABELS[status]||status)+'</span></div></div></div></section>'+
 '<table class="items"><thead><tr><th>ردیف</th><th>شرح سفارش</th><th>تعداد</th><th>قیمت واحد</th><th>مبلغ</th></tr></thead><tbody>'+rows+'</tbody></table>'+
 '<table class="totals"><tr><td>تعداد سفارش</td><td>۱ سفارش</td></tr><tr><td>تعداد کل اقلام</td><td>'+money(totalQty)+' عدد</td></tr><tr><td>جمع کالاها</td><td>'+money(subtotal)+' ریال</td></tr><tr><td>تخفیف</td><td>'+money(discount)+' ریال</td></tr><tr><td>هزینه ارسال</td><td>'+money(shipping)+' ریال</td></tr><tr class="grand"><td>جمع کل</td><td>'+money(total)+' ریال</td></tr></table>'+
 '<footer class="footer"><div class="note">این سند بر اساس اطلاعات ثبت‌شده در سامانه گیلاس آرت تهیه شده است. '+(status==='PENDING'?'تا پیش از تأیید پرداخت، این سند «پیش‌فاکتور فروش» محسوب می‌شود.':'پرداخت سفارش در سامانه ثبت شده و این سند «فاکتور فروش» است.')+'</div><div class="sign"><img src="'+esc(signaturePath)+'" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'block\'"><div class="fallback" style="display:none">مهر و امضای مدیرعامل<br>گیلاس آرت</div></div></footer></main></body></html>';
 const blob=new Blob([html],{type:'text/html;charset=utf-8'});
 const url=URL.createObjectURL(blob);
 const w=window.open(url,'_blank','width=1000,height=900');
 if(!w){URL.revokeObjectURL(url);alert('مرورگر اجازه باز شدن فاکتور را نداد. لطفاً پنجره‌های بازشو را برای سایت فعال کنید.');return}
 setTimeout(()=>{try{w.focus()}catch{}},150);
 setTimeout(()=>URL.revokeObjectURL(url),60000);
}
export {openInvoice};
